CREATE TABLE accounts (account_id UUID PRIMARY KEY, root_public_key BYTEA NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE devices (device_id UUID PRIMARY KEY, account_id UUID NOT NULL REFERENCES accounts ON DELETE CASCADE, device_public_key BYTEA NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), revoked_at TIMESTAMPTZ);
CREATE INDEX devices_account_idx ON devices(account_id) WHERE revoked_at IS NULL;
CREATE TABLE device_certificates (certificate_id UUID PRIMARY KEY, device_id UUID NOT NULL REFERENCES devices ON DELETE CASCADE, certificate BYTEA NOT NULL, expires_at TIMESTAMPTZ NOT NULL);
CREATE TABLE usernames (username TEXT PRIMARY KEY, account_id UUID NOT NULL UNIQUE REFERENCES accounts ON DELETE CASCADE, verified_at TIMESTAMPTZ NOT NULL);
CREATE TABLE auth_challenges (challenge_id UUID PRIMARY KEY, device_id UUID NOT NULL REFERENCES devices ON DELETE CASCADE, challenge BYTEA NOT NULL UNIQUE, expires_at TIMESTAMPTZ NOT NULL, consumed_at TIMESTAMPTZ);
CREATE INDEX auth_challenges_live_idx ON auth_challenges(device_id,expires_at) WHERE consumed_at IS NULL;
CREATE TABLE refresh_sessions (session_id UUID PRIMARY KEY, device_id UUID NOT NULL REFERENCES devices ON DELETE CASCADE, token_hash BYTEA NOT NULL UNIQUE, rotated_from UUID REFERENCES refresh_sessions, expires_at TIMESTAMPTZ NOT NULL, revoked_at TIMESTAMPTZ);
CREATE TABLE key_packages (package_id UUID PRIMARY KEY, device_id UUID NOT NULL REFERENCES devices ON DELETE CASCADE, package BYTEA NOT NULL, consumed_at TIMESTAMPTZ);
CREATE TABLE groups (group_id UUID PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE group_members (group_id UUID NOT NULL REFERENCES groups ON DELETE CASCADE, account_id UUID NOT NULL REFERENCES accounts, role SMALLINT NOT NULL, PRIMARY KEY(group_id,account_id));
CREATE TABLE group_events (event_id UUID PRIMARY KEY, group_id UUID NOT NULL REFERENCES groups ON DELETE CASCADE, author_device_id UUID NOT NULL REFERENCES devices, client_message_id UUID NOT NULL, ciphertext BYTEA NOT NULL, created_client_time BIGINT, received_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(author_device_id,client_message_id));
CREATE INDEX group_events_sync_idx ON group_events(group_id,received_at,event_id);
CREATE TABLE device_group_cursors (device_id UUID NOT NULL REFERENCES devices ON DELETE CASCADE, group_id UUID NOT NULL REFERENCES groups ON DELETE CASCADE, cursor_event_id UUID, updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), PRIMARY KEY(device_id,group_id));
CREATE TABLE message_receipts (event_id UUID NOT NULL REFERENCES group_events ON DELETE CASCADE, device_id UUID NOT NULL REFERENCES devices ON DELETE CASCADE, receipt_type SMALLINT NOT NULL, PRIMARY KEY(event_id,device_id,receipt_type));
CREATE TABLE relay_directory_versions (version BIGINT PRIMARY KEY, published_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE relay_endpoints (endpoint_id UUID PRIMARY KEY, directory_version BIGINT NOT NULL REFERENCES relay_directory_versions, endpoint BYTEA NOT NULL, enabled BOOLEAN NOT NULL DEFAULT true);
CREATE TABLE push_tokens (device_id UUID PRIMARY KEY REFERENCES devices ON DELETE CASCADE, token_hash BYTEA NOT NULL UNIQUE, platform SMALLINT NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE blocked_accounts (account_id UUID NOT NULL REFERENCES accounts ON DELETE CASCADE, blocked_account_id UUID NOT NULL REFERENCES accounts ON DELETE CASCADE, PRIMARY KEY(account_id,blocked_account_id));
CREATE TABLE abuse_counters (scope BYTEA PRIMARY KEY, window_start TIMESTAMPTZ NOT NULL, count INTEGER NOT NULL CHECK(count>=0));
