#![forbid(unsafe_code)]
//! Stable, pointer-free Swift/Kotlin API generated by UniFFI.

use messenger_core::{CachedRelayDirectory, IncomingEvent, MessengerCore, NetworkMode};
use messenger_crypto::{CryptoEngine, IncomingMessage, MemberCredential};
use std::sync::Mutex;
use thiserror::Error;

#[derive(Debug, Error, uniffi::Error)]
pub enum FfiError {
    #[error("invalid input")]
    InvalidInput,
    #[error("cryptographic operation failed")]
    Crypto,
    #[error("local storage operation failed")]
    Storage,
}

#[uniffi::export]
pub fn protocol_round_trip(frame: Vec<u8>) -> Result<Vec<u8>, FfiError> {
    let decoded =
        messenger_protocol::TransportFrame::decode(&frame).map_err(|_| FfiError::InvalidInput)?;
    decoded.encode().map_err(|_| FfiError::InvalidInput)
}

#[derive(Clone, uniffi::Record)]
pub struct FfiMemberCredential {
    pub device_id: Vec<u8>,
    pub account_id: Vec<u8>,
    pub certificate_fingerprint: Vec<u8>,
}

#[derive(Clone, uniffi::Record)]
pub struct FfiDeviceCertificate {
    pub device_id: Vec<u8>,
    pub device_public_key: Vec<u8>,
    pub issued_at: u64,
    pub signature: Vec<u8>,
}

#[derive(Clone, uniffi::Enum)]
pub enum FfiNetworkMode {
    Normal,
    Limited,
    Survival,
}

#[derive(Clone, uniffi::Record)]
pub struct FfiLocalMessage {
    pub client_message_id: Vec<u8>,
    pub conversation_id: Vec<u8>,
    pub plaintext: String,
    pub status: String,
    pub created_at_ms: i64,
}

#[derive(Clone, uniffi::Record)]
pub struct FfiPendingUpload {
    pub client_message_id: Vec<u8>,
    pub conversation_id: Vec<u8>,
    pub encrypted_payload: Vec<u8>,
    pub attempts: u32,
}

#[derive(Clone, uniffi::Record)]
pub struct FfiNetworkDiagnostics {
    pub mode: FfiNetworkMode,
    pub pending_uploads: u64,
    pub last_cursor: u64,
}
#[derive(Clone, uniffi::Record)]
pub struct FfiConversation {
    pub conversation_id: Vec<u8>,
    pub updated_at_ms: i64,
}
#[derive(Clone, uniffi::Record)]
pub struct FfiIncomingEvent {
    pub event_id: Vec<u8>,
    pub conversation_id: Vec<u8>,
    pub encrypted_event: Vec<u8>,
}

impl TryFrom<FfiMemberCredential> for MemberCredential {
    type Error = FfiError;
    fn try_from(value: FfiMemberCredential) -> Result<Self, Self::Error> {
        Ok(Self {
            device_id: value
                .device_id
                .try_into()
                .map_err(|_| FfiError::InvalidInput)?,
            account_id: value
                .account_id
                .try_into()
                .map_err(|_| FfiError::InvalidInput)?,
            certificate_fingerprint: value
                .certificate_fingerprint
                .try_into()
                .map_err(|_| FfiError::InvalidInput)?,
        })
    }
}

#[derive(uniffi::Object)]
pub struct MlsDevice {
    engine: Mutex<CryptoEngine>,
}

#[derive(uniffi::Object)]
pub struct LocalMessenger {
    core: MessengerCore,
}

#[uniffi::export]
impl LocalMessenger {
    #[uniffi::constructor]
    pub fn open(storage_path: String, master_key: Vec<u8>) -> Result<Self, FfiError> {
        Ok(Self {
            core: MessengerCore::open(storage_path, &master_key).map_err(|_| FfiError::Storage)?,
        })
    }
    pub fn create_message(
        &self,
        conversation_id: Vec<u8>,
        plaintext: String,
    ) -> Result<Vec<u8>, FfiError> {
        let conversation = conversation_id
            .try_into()
            .map_err(|_| FfiError::InvalidInput)?;
        Ok(self
            .core
            .create_message(conversation, &plaintext)
            .map_err(|_| FfiError::Storage)?
            .to_vec())
    }
    pub fn list_messages(
        &self,
        conversation_id: Vec<u8>,
    ) -> Result<Vec<FfiLocalMessage>, FfiError> {
        let conversation = conversation_id
            .try_into()
            .map_err(|_| FfiError::InvalidInput)?;
        self.core
            .list_messages(conversation)
            .map_err(|_| FfiError::Storage)
            .map(|values| {
                values
                    .into_iter()
                    .map(|value| FfiLocalMessage {
                        client_message_id: value.client_message_id.to_vec(),
                        conversation_id: value.conversation_id.to_vec(),
                        plaintext: value.plaintext,
                        status: format!("{:?}", value.status),
                        created_at_ms: value.created_at_ms,
                    })
                    .collect()
            })
    }
    pub fn list_conversations(&self) -> Result<Vec<FfiConversation>, FfiError> {
        self.core
            .list_conversations()
            .map_err(|_| FfiError::Storage)
            .map(|values| {
                values
                    .into_iter()
                    .map(|value| FfiConversation {
                        conversation_id: value.conversation_id.to_vec(),
                        updated_at_ms: value.updated_at_ms,
                    })
                    .collect()
            })
    }
    pub fn observe_conversation_changes(&self, after_revision: u64) -> Result<u64, FfiError> {
        self.core
            .observe_conversation_changes(after_revision)
            .map_err(|_| FfiError::Storage)
    }
    pub fn create_group(&self, group_id: Vec<u8>) -> Result<(), FfiError> {
        self.core
            .create_group(group_id.try_into().map_err(|_| FfiError::InvalidInput)?)
            .map_err(|_| FfiError::Storage)
    }
    pub fn add_member(
        &self,
        group_id: Vec<u8>,
        device_id: Vec<u8>,
        account_id: Vec<u8>,
    ) -> Result<(), FfiError> {
        self.core
            .add_member(
                group_id.try_into().map_err(|_| FfiError::InvalidInput)?,
                device_id.try_into().map_err(|_| FfiError::InvalidInput)?,
                account_id.try_into().map_err(|_| FfiError::InvalidInput)?,
            )
            .map_err(|_| FfiError::Storage)
    }
    pub fn remove_member(&self, group_id: Vec<u8>, device_id: Vec<u8>) -> Result<(), FfiError> {
        self.core
            .remove_member(
                group_id.try_into().map_err(|_| FfiError::InvalidInput)?,
                device_id.try_into().map_err(|_| FfiError::InvalidInput)?,
            )
            .map_err(|_| FfiError::Storage)
    }
    pub fn get_pending_uploads(&self) -> Result<Vec<FfiPendingUpload>, FfiError> {
        self.core
            .get_pending_uploads(50)
            .map_err(|_| FfiError::Storage)
            .map(|values| {
                values
                    .into_iter()
                    .map(|value| FfiPendingUpload {
                        client_message_id: value.client_message_id.to_vec(),
                        conversation_id: value.conversation_id.to_vec(),
                        encrypted_payload: value.encrypted_payload,
                        attempts: value.attempts,
                    })
                    .collect()
            })
    }
    pub fn mark_upload_accepted(&self, message_id: Vec<u8>) -> Result<(), FfiError> {
        self.core
            .mark_upload_accepted(message_id.try_into().map_err(|_| FfiError::InvalidInput)?)
            .map_err(|_| FfiError::Storage)
    }
    pub fn retry_message(&self, message_id: Vec<u8>) -> Result<(), FfiError> {
        self.core
            .retry_message(message_id.try_into().map_err(|_| FfiError::InvalidInput)?)
            .map_err(|_| FfiError::Storage)
    }
    pub fn cancel_pending_message(&self, message_id: Vec<u8>) -> Result<(), FfiError> {
        self.core
            .cancel_pending_message(message_id.try_into().map_err(|_| FfiError::InvalidInput)?)
            .map_err(|_| FfiError::Storage)
    }
    pub fn ingest_server_event(
        &self,
        event_id: Vec<u8>,
        conversation_id: Vec<u8>,
        ciphertext: Vec<u8>,
    ) -> Result<bool, FfiError> {
        self.core
            .ingest_server_event(
                event_id.try_into().map_err(|_| FfiError::InvalidInput)?,
                conversation_id
                    .try_into()
                    .map_err(|_| FfiError::InvalidInput)?,
                &ciphertext,
            )
            .map_err(|_| FfiError::Storage)
    }
    pub fn ingest_server_batch(&self, events: Vec<FfiIncomingEvent>) -> Result<u64, FfiError> {
        let converted = events
            .into_iter()
            .map(|event| {
                Ok(IncomingEvent {
                    event_id: event
                        .event_id
                        .try_into()
                        .map_err(|_| FfiError::InvalidInput)?,
                    conversation_id: event
                        .conversation_id
                        .try_into()
                        .map_err(|_| FfiError::InvalidInput)?,
                    encrypted_event: event.encrypted_event,
                })
            })
            .collect::<Result<Vec<_>, FfiError>>()?;
        self.core
            .ingest_server_batch(&converted)
            .map(|value| value as u64)
            .map_err(|_| FfiError::Storage)
    }
    pub fn apply_delivery_receipt(&self, message_id: Vec<u8>) -> Result<(), FfiError> {
        self.core
            .apply_delivery_receipt(message_id.try_into().map_err(|_| FfiError::InvalidInput)?)
            .map_err(|_| FfiError::Storage)
    }
    pub fn apply_read_receipt(&self, message_id: Vec<u8>) -> Result<(), FfiError> {
        self.core
            .apply_read_receipt(message_id.try_into().map_err(|_| FfiError::InvalidInput)?)
            .map_err(|_| FfiError::Storage)
    }
    pub fn block_account(&self, account_id: Vec<u8>) -> Result<(), FfiError> {
        self.core
            .block_account(account_id.try_into().map_err(|_| FfiError::InvalidInput)?)
            .map_err(|_| FfiError::Storage)
    }
    pub fn unblock_account(&self, account_id: Vec<u8>) -> Result<(), FfiError> {
        self.core
            .unblock_account(account_id.try_into().map_err(|_| FfiError::InvalidInput)?)
            .map_err(|_| FfiError::Storage)
    }
    pub fn set_network_mode(&self, mode: FfiNetworkMode) -> Result<(), FfiError> {
        self.core
            .set_network_mode(match mode {
                FfiNetworkMode::Normal => NetworkMode::Normal,
                FfiNetworkMode::Limited => NetworkMode::Limited,
                FfiNetworkMode::Survival => NetworkMode::Survival,
            })
            .map_err(|_| FfiError::Storage)
    }
    pub fn get_network_diagnostics(&self) -> Result<FfiNetworkDiagnostics, FfiError> {
        let value = self
            .core
            .get_network_diagnostics()
            .map_err(|_| FfiError::Storage)?;
        Ok(FfiNetworkDiagnostics {
            mode: match value.mode {
                NetworkMode::Normal => FfiNetworkMode::Normal,
                NetworkMode::Limited => FfiNetworkMode::Limited,
                NetworkMode::Survival => FfiNetworkMode::Survival,
            },
            pending_uploads: value.pending_uploads,
            last_cursor: value.last_cursor,
        })
    }
    pub fn cache_relay_directory(
        &self,
        version: u64,
        signed_directory: Vec<u8>,
        expires_at_ms: i64,
    ) -> Result<(), FfiError> {
        self.core
            .cache_relay_directory(&CachedRelayDirectory {
                version,
                signed_directory,
                expires_at_ms,
            })
            .map_err(|_| FfiError::Storage)
    }
    pub fn rotate_local_master_key(
        &self,
        new_key: Vec<u8>,
        new_version: u32,
    ) -> Result<(), FfiError> {
        self.core
            .rotate_master_key(&new_key, new_version)
            .map_err(|_| FfiError::Storage)
    }
    pub fn wipe_local_account(&self) -> Result<(), FfiError> {
        self.core
            .wipe_local_account()
            .map_err(|_| FfiError::Storage)
    }
}

#[uniffi::export]
impl MlsDevice {
    #[uniffi::constructor]
    pub fn initialize_crypto_store(
        member: FfiMemberCredential,
        state_key: Vec<u8>,
    ) -> Result<Self, FfiError> {
        let state_key = state_key.try_into().map_err(|_| FfiError::InvalidInput)?;
        let engine = CryptoEngine::initialize_crypto_store(member.try_into()?, state_key)
            .map_err(|_| FfiError::Crypto)?;
        Ok(Self {
            engine: Mutex::new(engine),
        })
    }

    pub fn generate_key_packages(&self, count: u32) -> Result<Vec<Vec<u8>>, FfiError> {
        self.engine
            .lock()
            .map_err(|_| FfiError::Crypto)?
            .generate_key_packages(count as usize)
            .map_err(|_| FfiError::Crypto)
    }

    pub fn export_public_key_packages(&self, count: u32) -> Result<Vec<Vec<u8>>, FfiError> {
        self.engine
            .lock()
            .map_err(|_| FfiError::Crypto)?
            .export_public_key_packages(count as usize)
            .map_err(|_| FfiError::Crypto)
    }

    pub fn create_conversation(&self, group_id: Vec<u8>) -> Result<(), FfiError> {
        self.engine
            .lock()
            .map_err(|_| FfiError::Crypto)?
            .create_conversation(&group_id)
            .map_err(|_| FfiError::Crypto)
    }

    pub fn commit_add_member(
        &self,
        group_id: Vec<u8>,
        key_package: Vec<u8>,
    ) -> Result<Vec<Vec<u8>>, FfiError> {
        let change = self
            .engine
            .lock()
            .map_err(|_| FfiError::Crypto)?
            .commit_add_members(&group_id, &[key_package])
            .map_err(|_| FfiError::Crypto)?;
        Ok(vec![change.commit, change.welcome.unwrap_or_default()])
    }

    pub fn propose_add_member(
        &self,
        group_id: Vec<u8>,
        key_package: Vec<u8>,
    ) -> Result<Vec<u8>, FfiError> {
        self.engine
            .lock()
            .map_err(|_| FfiError::Crypto)?
            .propose_add_members(&group_id, &key_package)
            .map_err(|_| FfiError::Crypto)
    }

    pub fn commit_remove_member(
        &self,
        group_id: Vec<u8>,
        member: FfiMemberCredential,
    ) -> Result<Vec<Vec<u8>>, FfiError> {
        let change = self
            .engine
            .lock()
            .map_err(|_| FfiError::Crypto)?
            .commit_remove_members(&group_id, &member.try_into()?)
            .map_err(|_| FfiError::Crypto)?;
        Ok(vec![change.commit, change.welcome.unwrap_or_default()])
    }

    pub fn propose_remove_member(
        &self,
        group_id: Vec<u8>,
        member: FfiMemberCredential,
    ) -> Result<Vec<u8>, FfiError> {
        self.engine
            .lock()
            .map_err(|_| FfiError::Crypto)?
            .propose_remove_members(&group_id, &member.try_into()?)
            .map_err(|_| FfiError::Crypto)
    }

    pub fn join_conversation_from_welcome(&self, welcome: Vec<u8>) -> Result<Vec<u8>, FfiError> {
        self.engine
            .lock()
            .map_err(|_| FfiError::Crypto)?
            .join_conversation_from_welcome(&welcome)
            .map_err(|_| FfiError::Crypto)
    }

    pub fn encrypt_application_message(
        &self,
        group_id: Vec<u8>,
        plaintext: Vec<u8>,
    ) -> Result<Vec<u8>, FfiError> {
        self.engine
            .lock()
            .map_err(|_| FfiError::Crypto)?
            .encrypt_application_message(&group_id, &plaintext)
            .map_err(|_| FfiError::Crypto)
    }

    pub fn process_incoming_message(
        &self,
        group_id: Vec<u8>,
        ciphertext: Vec<u8>,
    ) -> Result<Vec<u8>, FfiError> {
        match self
            .engine
            .lock()
            .map_err(|_| FfiError::Crypto)?
            .process_incoming_message(&group_id, &ciphertext)
            .map_err(|_| FfiError::Crypto)?
        {
            IncomingMessage::Application(value) => Ok(value),
            _ => Ok(Vec::new()),
        }
    }

    pub fn export_conversation_state(&self, group_id: Vec<u8>) -> Result<Vec<u8>, FfiError> {
        self.engine
            .lock()
            .map_err(|_| FfiError::Crypto)?
            .export_conversation_state(&group_id)
            .map_err(|_| FfiError::Crypto)
    }

    pub fn import_conversation_state(&self, snapshot: Vec<u8>) -> Result<Vec<u8>, FfiError> {
        self.engine
            .lock()
            .map_err(|_| FfiError::Crypto)?
            .import_conversation_state(&snapshot)
            .map_err(|_| FfiError::Crypto)
    }

    pub fn get_conversation_epoch(&self, group_id: Vec<u8>) -> Result<u64, FfiError> {
        self.engine
            .lock()
            .map_err(|_| FfiError::Crypto)?
            .get_conversation_epoch(&group_id)
            .map_err(|_| FfiError::Crypto)
    }

    pub fn self_update(&self, group_id: Vec<u8>) -> Result<Vec<u8>, FfiError> {
        self.engine
            .lock()
            .map_err(|_| FfiError::Crypto)?
            .self_update(&group_id)
            .map_err(|_| FfiError::Crypto)
    }

    pub fn verify_member_credential(
        &self,
        encoded: Vec<u8>,
        root_public_key: Vec<u8>,
        certificate: FfiDeviceCertificate,
    ) -> Result<FfiMemberCredential, FfiError> {
        let root_public_key = root_public_key
            .try_into()
            .map_err(|_| FfiError::InvalidInput)?;
        let certificate = messenger_identity::DeviceCertificate {
            device_id: certificate
                .device_id
                .try_into()
                .map_err(|_| FfiError::InvalidInput)?,
            device_public_key: certificate
                .device_public_key
                .try_into()
                .map_err(|_| FfiError::InvalidInput)?,
            issued_at: certificate.issued_at,
            signature: certificate
                .signature
                .try_into()
                .map_err(|_| FfiError::InvalidInput)?,
        };
        let member = self
            .engine
            .lock()
            .map_err(|_| FfiError::Crypto)?
            .verify_member_credential(&encoded, &root_public_key, &certificate)
            .map_err(|_| FfiError::Crypto)?;
        Ok(FfiMemberCredential {
            device_id: member.device_id.to_vec(),
            account_id: member.account_id.to_vec(),
            certificate_fingerprint: member.certificate_fingerprint.to_vec(),
        })
    }

    pub fn destroy_local_conversation_state(&self, group_id: Vec<u8>) -> Result<(), FfiError> {
        self.engine
            .lock()
            .map_err(|_| FfiError::Crypto)?
            .destroy_local_conversation_state(&group_id)
            .map_err(|_| FfiError::Crypto)
    }
}

uniffi::setup_scaffolding!();

#[cfg(test)]
mod tests {
    use super::*;
    fn member(seed: u8) -> FfiMemberCredential {
        FfiMemberCredential {
            device_id: vec![seed; 16],
            account_id: vec![seed; 32],
            certificate_fingerprint: vec![seed; 16],
        }
    }
    #[test]
    fn ffi_surface_calls_real_openmls() {
        let alice = MlsDevice::initialize_crypto_store(member(1), vec![1; 32]).unwrap();
        let bob = MlsDevice::initialize_crypto_store(member(2), vec![2; 32]).unwrap();
        let package = bob.generate_key_packages(1).unwrap().remove(0);
        alice.create_conversation(b"ffi-test".to_vec()).unwrap();
        let change = alice
            .commit_add_member(b"ffi-test".to_vec(), package)
            .unwrap();
        bob.join_conversation_from_welcome(change[1].clone())
            .unwrap();
        let encrypted = alice
            .encrypt_application_message(b"ffi-test".to_vec(), b"real MLS".to_vec())
            .unwrap();
        assert_eq!(
            bob.process_incoming_message(b"ffi-test".to_vec(), encrypted)
                .unwrap(),
            b"real MLS"
        );
        let ping = hex("8601010e50070707070707070707070707070707070040");
        assert_eq!(protocol_round_trip(ping.clone()).unwrap(), ping);
    }
    fn hex(value: &str) -> Vec<u8> {
        (0..value.len())
            .step_by(2)
            .map(|index| u8::from_str_radix(&value[index..index + 2], 16).unwrap())
            .collect()
    }
}
