#![forbid(unsafe_code)]
//! Client-owned anonymous identity. Root secrets and recovery phrases never leave this crate.
use std::time::{SystemTime,UNIX_EPOCH};
use bip39::{Language,Mnemonic}; use chacha20poly1305::{aead::{Aead,KeyInit},XChaCha20Poly1305,XNonce};
use ed25519_dalek::{Signature,Signer,SigningKey,Verifier,VerifyingKey}; use hkdf::Hkdf; use rand_core::{OsRng,RngCore}; use sha2::{Digest,Sha256}; use unicode_normalization::UnicodeNormalization;
pub const ACCOUNT_ID_DOMAIN:&[u8]=b"resilient/account-id/v1";
#[derive(Clone)] pub struct AccountRoot(pub SigningKey); #[derive(Clone)] pub struct DeviceKey(pub SigningKey);
#[derive(Clone,Debug)] pub struct DeviceCertificate{pub device_id:[u8;16],pub device_public_key:[u8;32],pub issued_at:u64,pub signature:[u8;64]}
#[derive(Clone,Debug)] pub struct SignedInvite{pub version:u8,pub account_id:[u8;32],pub fingerprint:[u8;16],pub expires_at:Option<u64>,pub signature:[u8;64]}
pub fn create_account()->(AccountRoot,DeviceKey,DeviceCertificate){let root=AccountRoot(SigningKey::generate(&mut OsRng));let device=DeviceKey(SigningKey::generate(&mut OsRng));let cert=sign_device_certificate(&root,&device);(root,device,cert)}
pub fn account_id(root:&AccountRoot)->[u8;32]{let mut h=Sha256::new();h.update(ACCOUNT_ID_DOMAIN);h.update(root.0.verifying_key().as_bytes());h.finalize().into()}
pub fn sign_device_certificate(root:&AccountRoot,device:&DeviceKey)->DeviceCertificate{let mut id=[0;16];OsRng.fill_bytes(&mut id);let issued=now();let mut v=Vec::new();v.extend_from_slice(&id);v.extend_from_slice(device.0.verifying_key().as_bytes());v.extend_from_slice(&issued.to_be_bytes());let sig=root.0.sign(&v).to_bytes();DeviceCertificate{device_id:id,device_public_key:device.0.verifying_key().to_bytes(),issued_at:issued,signature:sig}}
pub fn verify_device_certificate(root_public:&[u8;32],cert:&DeviceCertificate)->bool{let Ok(root)=VerifyingKey::from_bytes(root_public)else{return false};let mut v=Vec::new();v.extend_from_slice(&cert.device_id);v.extend_from_slice(&cert.device_public_key);v.extend_from_slice(&cert.issued_at.to_be_bytes());root.verify(&v,&Signature::from_bytes(&cert.signature)).is_ok()}
pub fn generate_recovery_phrase()->Mnemonic{Mnemonic::generate_in(Language::English,24).expect("supported entropy")}
pub fn recovery_identifier(phrase:&Mnemonic)->[u8;32]{let mut h=Sha256::new();h.update(b"resilient/recovery-id/v1");h.update(phrase.to_entropy());h.finalize().into()}
pub fn encrypt_recovery_blob(phrase:&Mnemonic,plaintext:&[u8])->Result<Vec<u8>,()> {let hk=Hkdf::<Sha256>::new(Some(b"resilient/recovery/salt/v1"),&phrase.to_entropy());let mut key=[0;32];hk.expand(b"recovery-blob",&mut key).map_err(|_|())?;let mut nonce=[0;24];OsRng.fill_bytes(&mut nonce);let c=XChaCha20Poly1305::new_from_slice(&key).map_err(|_|())?;let mut out=nonce.to_vec();out.extend(c.encrypt(XNonce::from_slice(&nonce),plaintext).map_err(|_|())?);Ok(out)}
pub fn decrypt_recovery_blob(phrase:&Mnemonic,blob:&[u8])->Result<Vec<u8>,()> {if blob.len()<24{return Err(())}let hk=Hkdf::<Sha256>::new(Some(b"resilient/recovery/salt/v1"),&phrase.to_entropy());let mut key=[0;32];hk.expand(b"recovery-blob",&mut key).map_err(|_|())?;XChaCha20Poly1305::new_from_slice(&key).map_err(|_|())?.decrypt(XNonce::from_slice(&blob[..24]),&blob[24..]).map_err(|_|())}
pub fn canonical_username(input:&str)->Result<String,()> {let v=input.nfkc().flat_map(char::to_lowercase).collect::<String>();if !(3..=32).contains(&v.chars().count())||v.chars().any(|c|c.is_control()||!(c.is_ascii_alphanumeric()||c=='_'||c=='.')){return Err(())}Ok(v)}
pub fn sign_invite(root:&AccountRoot,expires_at:Option<u64>)->SignedInvite{let id=account_id(root);let mut fp=[0;16];fp.copy_from_slice(&root.0.verifying_key().as_bytes()[..16]);let mut v=vec![1];v.extend_from_slice(&id);v.extend_from_slice(&fp);v.extend_from_slice(&expires_at.unwrap_or(0).to_be_bytes());let s=root.0.sign(&v).to_bytes();SignedInvite{version:1,account_id:id,fingerprint:fp,expires_at,signature:s}}
pub fn verify_invite(root_public:&[u8;32],invite:&SignedInvite,at:u64)->bool{if invite.version!=1||invite.expires_at.is_some_and(|x|x<at){return false}let Ok(root)=VerifyingKey::from_bytes(root_public)else{return false};let mut v=vec![invite.version];v.extend_from_slice(&invite.account_id);v.extend_from_slice(&invite.fingerprint);v.extend_from_slice(&invite.expires_at.unwrap_or(0).to_be_bytes());root.verify(&v,&Signature::from_bytes(&invite.signature)).is_ok()}
fn now()->u64{SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_secs()}
#[cfg(test)]mod tests{use super::*;#[test]fn identity_and_recovery(){let(r,_,c)=create_account();assert!(verify_device_certificate(&r.0.verifying_key().to_bytes(),&c));let p=generate_recovery_phrase();let x=encrypt_recovery_blob(&p,b"root key backup").unwrap();assert_eq!(decrypt_recovery_blob(&p,&x).unwrap(),b"root key backup");assert!(canonical_username("Test_Name").is_ok());assert_eq!(canonical_username("teSt").unwrap(),"test")}#[test]fn tampering_fails(){let(r,_,_)=create_account();let mut i=sign_invite(&r,None);i.account_id[0]^=1;assert!(!verify_invite(&r.0.verifying_key().to_bytes(),&i,0))}}
